---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Batch components for FPE'
Parameters:
  vpcId:
    Type: String
    Default: vpc-0bbf7e0e987fdcb66
  subnetIds:
    Type: CommaDelimitedList
    Default: 'subnet-06821c12e0348081f,subnet-04a189a052284439c'
Resources:
  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group for instances launched by Batch
      VpcId: !Ref vpcId
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: fpe-batch-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: batch.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: fpe-batch-execution-role
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  JobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: fpe-batch-job-role
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite
  BatchJobDefinition:
    # https://docs.aws.amazon.com/batch/latest/userguide/fargate.html
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: fpe-batch-job-definition
      PlatformCapabilities:
        - FARGATE
      ContainerProperties:
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${BatchRepository}:latest
        ExecutionRoleArn: !GetAtt [ExecutionRole, Arn]
        JobRoleArn: !GetAtt [JobRole, Arn]
        FargatePlatformConfiguration:
          PlatformVersion: LATEST
        ResourceRequirements:
          - Type: MEMORY
            Value: 1024
          - Type: VCPU
            Value: 0.25
        Command:
          - node
          - process.js
        NetworkConfiguration:
          AssignPublicIp: ENABLED
        Environment:
          - Name: REGION
            Value: !Ref AWS::Region
      RetryStrategy:
        Attempts: 1
  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: fpe-batch-job-queue
      Priority: 1
      ComputeEnvironmentOrder:
      - Order: 1
        ComputeEnvironment:
          Ref: ComputeEnvironment
  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: fpe-batch-compute-environment
      Type: MANAGED
      ComputeResources:
        Type: FARGATE
        MaxvCpus: 32
        Subnets: !Ref subnetIds
        SecurityGroupIds:
        - Ref: BatchSecurityGroup
      ServiceRole:
        Ref: BatchServiceRole
  BatchRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: fpe-batch
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          -
            Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
               - !Sub arn:aws:iam::${AWS::AccountId}:role/${ExecutionRole}
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
Outputs:
  ComputeEnvironmentArn:
    Value: !Ref ComputeEnvironment
  BatchJobQueueArn:
    Value: !Ref BatchJobQueue
  BatchJobDefinitionArn:
    Value: !Ref BatchJobDefinition
  BatchRepository:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${BatchRepository}
