AWSTemplateFormatVersion: 2010-09-09
Description: Lambda function to process datasets for FPE
Parameters:
  functionName:
    Type: String
    Default: fpe-lambda-dataset
  storageBucket:
    Type: String
    Default: walkerenvres-fpe-storage
  securityGroupId:
    Type: String
    Default: sg-04c571df12b1778c5
  subnetIds:
    Type: CommaDelimitedList
    Default: subnet-0c14f9d14103e7827
  roleName:
    Type: String
    Default: fpe-lambda-dataset-role
  policyName:
    Type: String
    Default: fpe-lambda-dataset-policy
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaExecutionRole
    Properties:
      FunctionName:
        Ref: functionName
      Tags:
      - Key: project
        Value: fpe
      - Key: env
        Value: dev
      Handler: index.handler
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
          FPE_DB_HOST: sheds-fpe.cysjjzu7kurm.us-east-1.rds.amazonaws.com
          FPE_DB_PORT: 5432
          FPE_DB_DATABASE: fpe
          FPE_DB_USER: jeff
          FPE_DB_PASSWORD: sheds-fpe
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: nodejs12.x
      Timeout: '60'
      MemorySize: '256'
      Code:
        S3Bucket: walkerenvres-fpe-lambda
        S3Key: 6018adcb8df1786f47ec59dc3a569dfb
      VpcConfig:
        SecurityGroupIds:
        - Ref: securityGroupId
        SubnetIds:
          Ref: subnetIds
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Ref: roleName
      Tags:
      - Key: project
        Value: fpe
      - Key: env
        Value: dev
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
  LambdaExecutionPolicy:
    Type: AWS::IAM::Policy
    DependsOn: LambdaExecutionRole
    Properties:
      PolicyName:
        Ref: policyName
      Roles:
      - Ref: LambdaExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource:
            Fn::Sub:
            - arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*
            - region:
                Ref: AWS::Region
              account:
                Ref: AWS::AccountId
              lambda:
                Ref: LambdaFunction
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource:
            Fn::Sub: arn:aws:s3:::${storageBucket}/*
Outputs:
  Region:
    Value:
      Ref: AWS::Region
  FunctionName:
    Value:
      Ref: LambdaFunction
  FunctionArn:
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Arn
