AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket for Data
Parameters:
  bucketName:
    Type: String
    Default: walkerenvres-fpe-data
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref bucketName
      Tags:
        - Key: project
          Value: fpe
        - Key: env
          Value: dev
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - POST
            AllowedOrigins:
              - '*'
            MaxAge: '3600'
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: fpe-s3-data-policy
        Version: '2012-10-17'
        Statement:
          - Sid: AllowPublicReadOnly
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/*']]
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the S3 bucket
