AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for deploying lambda code
Parameters:
  bucketName:
    Type: String
    Default: walkerenvres-fpe-lambda
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref bucketName
      Tags:
        - Key: project
          Value: fpe
        - Key: env
          Value: dev
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the S3 bucket