AWSTemplateFormatVersion: 2010-09-09
Description: Lambda function for FPE API
Parameters:
  vpcId:
    Type: String
    Default: vpc-0bbf7e0e987fdcb66
  subnetIds:
    Type: CommaDelimitedList
    Default: subnet-0052282d1c0eefc84
  dbSecretArn:
    Type: String
    Default: arn:aws:secretsmanager:us-east-1:474916309046:secret:fpe-rds-secret-jO8YDC
  jobDefinitionArn:
    Type: String
    Default: arn:aws:batch:us-east-1:474916309046:job-definition/fpe-batch-job-definition:*
  jobQueueArn:
    Type: String
    Default: arn:aws:batch:us-east-1:474916309046:job-queue/fpe-batch-job-queue
  functionName:
    Type: String
    Default: fpe-lambda-api
  roleName:
    Type: String
    Default: fpe-lambda-api-role
  policyName:
    Type: String
    Default: fpe-lambda-api-policy
  dataBucket:
    Type: String
    Default: walkerenvres-fpe-data
  workerFunctionName:
    Type: String
    Default: fpe-lambda-worker
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow lambda access to vpc
      VpcId:
        Ref: vpcId
  LambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaExecutionRole
    Properties:
      FunctionName:
        Ref: functionName
      Tags:
      - Key: project
        Value: fpe
      - Key: env
        Value: dev
      Handler: lambda.handler
      Environment:
        Variables:
          FPE_REGION:
            Ref: AWS::Region
          FPE_S3_BUCKET:
            Ref: dataBucket
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: nodejs14.x
      Timeout: '15'
      Code:
        S3Bucket: walkerenvres-fpe-lambda
        S3Key: api/1c5c010bcf82051b40019293fae58d09
      VpcConfig:
        SecurityGroupIds:
        - Ref: SecurityGroup
        SubnetIds:
          Ref: subnetIds
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Ref: roleName
      Tags:
      - Key: project
        Value: fpe
      - Key: env
        Value: dev
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
  LambdaExecutionPolicy:
    Type: AWS::IAM::Policy
    DependsOn: LambdaExecutionRole
    Properties:
      PolicyName:
        Ref: policyName
      Roles:
      - Ref: LambdaExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource:
            Fn::Sub:
            - arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*
            - region:
                Ref: AWS::Region
              account:
                Ref: AWS::AccountId
              lambda:
                Ref: LambdaFunction
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:PutObject
          - s3:DeleteObject
          - s3:ListBucket
          Resource:
          - Fn::Sub: arn:aws:s3:::${dataBucket}
          - Fn::Sub: arn:aws:s3:::${dataBucket}/*
        - Effect: Allow
          Action:
          - secretsmanager:GetResourcePolicy
          - secretsmanager:GetSecretValue
          - secretsmanager:DescribeSecret
          - secretsmanager:ListSecretVersionIds
          Resource:
            Ref: dbSecretArn
        - Effect: Allow
          Action:
          - batch:*
          Resource: '*'
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:lambda:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - ':function:'
              - Ref: workerFunctionName
Outputs:
  Region:
    Value:
      Ref: AWS::Region
  FunctionName:
    Value:
      Ref: LambdaFunction
  FunctionArn:
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Arn
